--- 
  :name: Fusor
  :description: ""
  :enabled: true
  :log_dir: /var/log/fusor-installer
  :log_name: fusor-installer.log
  :log_level: debug
  :no_prefix: false
  :mapping: {}
  :answer_file: /etc/fusor-installer/fusor-installer.answers.yaml
  :installer_dir: /usr/share/fusor-installer
  :module_dirs: 
    - /usr/share/fusor-installer/modules
    - /usr/share/foreman-installer/modules
  :default_values_dir: /tmp
  :colors: true
  :color_of_background: :dark
  :hook_dirs: []
  :custom: {}
  :low_priority_modules: []
  :verbose_log_level: debug
  :parser_cache_path: "./config/parser_cache.json"
  :password: H69G9HAWaY0xeIefmGfRHTuur8IVYVAfesZonHwZFSQ
  :provisioning_wizard: interactive